version: "3"

services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8080:8080"
    command:
      [
        "CompileDaemon",
        "-directory=./src",
        "-build=go build -o ../bin/server",
        "-command=./bin/server",
      ]
    volumes:
      - .:/usr/src/app
